# Site settings
title: Open Source Design - Job Board
email: osd@job-board.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of Open Source Design jobs
baseurl: "/jobs" # the subpath of your site, e.g. /blog/
url: "http://opensourcedesign.github.io" # the base hostname & protocol for your site
twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown

kramdown:
  input: GFM
